### ISSUE TITLE
error

### ISSUE THREAD

**Issue by etelo** [Joey0x646576/MemoryMapper-Example#1]
{"Side":2,"S1":-0.09,"S2":0,"S1sum":-0.09,"S2sum":0,"SumT":0}
{"Side":0,"S1":0      ,"S2":0,"S1sum":-0.09,"S2sum":0,"SumT":0}":0}

there are three characters left from the previous file:  ":0}

**Comment by Joey0x646576** [comment]
Hi @etelo 

Are you by chance (re)writing to the same file? The length is set on the initial creation, that would explain the additional `:0}`

**Comment by etelo** [comment]
I can not imagine how to cope with this without crutches. Maybe you have some ideas?

**Comment by Joey0x646576** [comment]
The `MemoryMapper.cs` is set to CreateOrOpen. There are various other ways to create a mapped file, see the methods section [here](https://learn.microsoft.com/en-us/dotnet/api/system.io.memorymappedfiles.memorymappedfile?view=net-6.0)

However I have no insight in what you are trying to achieve. So I can't steer you in the right direction.
